### ISSUE TITLE
Resize figcaption

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#18]
Check out [A School for Vernacular Algorithms](https://criticalcode.recipes/contributions/a-school-for-vernacular-algorithms) as an example – would it be possible to resize figcaption so that the caption width is contained by image width?
<img width="1039" alt="Screen Shot 2022-06-22 at 11 10 45 PM" src="https://user-images.githubusercontent.com/9159424/175223738-b2bf09fd-62b8-48a5-8c85-a55d39e0e831.png">

When I add captions using layout blocks that is done automatically, but it's currently not supported by the default text editor. 
<img width="478" alt="Screen Shot 2022-06-22 at 11 45 48 PM" src="https://user-images.githubusercontent.com/9159424/175224178-4f40ddf3-1bbc-435b-9c52-5e7b8b6f0639.png">

Also, the figcaption paddings seem to slightly differ between the two.

**Comment by Kcaden20** [comment]
Fixed! Both Strokes now wrap around the `figure` and the figcaption spacing is aligned. Along with this, I've made it so that all images in projects now have a lightbox on them allowing them to be inspected at a larger size.  Before this was only possible with layout figure blocks. 

![Screen Shot 2022-06-23 at 4 15 41 PM](https://user-images.githubusercontent.com/13590895/175392968-911cf021-bad1-42b8-9ee6-27b74c54aadf.png)![Screen Shot 2022-06-23 at 4 15 23 PM](https://user-images.githubusercontent.com/13590895/175392972-068f23c6-6b0b-47c1-9110-18bfb954fc4b.png)
![Screen Shot 2022-06-23 at 4 15 53 PM](https://user-images.githubusercontent.com/13590895/175392963-5d63a61a-d72f-4149-9b14-888fdfd5afb2.png)
