### ISSUE TITLE
Filter buttons

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#33]
A couple styling suggestions for the filter buttons:

- remove automated capitalization for the filter buttons
- for desktop, make two rows with even number of buttons – 5 btns on top and 5 btns on the bottom (a slightly different arrangement might be needed for mobile)
- make "code-agnostic" display in a single line so that the button isn't taller than the rest

<img width="1245" alt="Screen Shot 2022-06-26 at 6 30 34 AM" src="https://user-images.githubusercontent.com/9159424/175814211-5101c550-bfb2-4a08-ae60-2fa39dd674ee.png">

**Comment by Kcaden20** [comment]
This has been changed so that at it's widest, it can accommodate 5 x 5. I prioritized keeping them all on one line and the same width so at narrower widths, the column—row amounts vary a little bit. 
![Screen Shot 2022-06-27 at 11 41 26 AM](https://user-images.githubusercontent.com/13590895/175980281-5f82cd27-066b-4acb-8d74-4acdac911bc9.png)
![Screen Shot 2022-06-27 at 11 41 16 AM](https://user-images.githubusercontent.com/13590895/175980283-3ab41868-d7be-45e8-b5ab-f4b971030646.png)

**Comment by Kcaden20** [comment]
For the `<400 ` devices, this feels like the compromise to make sure that users don't have to scroll through a bunch of filter buttons before getting to the content. 
![Screen Shot 2022-06-27 at 11 49 36 AM](https://user-images.githubusercontent.com/13590895/175981326-87a85979-9762-4a18-905f-71286e40c2b7.png)

**Comment by xinemata** [comment]
The new layouts for desktop & mobile looks good on my end! 

The capitalization has changed to all low caps – is there a way for it to follow what's been typed into the Coding Language from Kirby backend?

<img width="601" alt="Screen Shot 2022-06-27 at 1 19 51 PM" src="https://user-images.githubusercontent.com/9159424/176019069-7abe3b92-c42b-4e17-aedc-a253d58138d9.png">
<img width="1264" alt="Screen Shot 2022-06-27 at 1 19 20 PM" src="https://user-images.githubusercontent.com/9159424/176018965-550e6b0c-5108-4651-9be7-d10b037d0096.png">

**Comment by Kcaden20** [comment]
Yes, can fix.

**Comment by Kcaden20** [comment]
@xinemata 
So the lowercasing happens because the website is pulling the `value` which is different than the `text` entered (which is really just displayed on the panel). Kirby on the backend turns this into a lower case word so that it can be inserted into a `URL` and used as a filter. 

I'm pulling from that and putting it on the FE which is why I had styling to re-capitalize it. I've now lowercased everything. 

EDIT: I also changed All to lowercase.
<img width="928" alt="Screen Shot 2022-06-27 at 5 55 54 PM" src="https://user-images.githubusercontent.com/13590895/176042873-6dd2a53a-9eb6-41e5-8038-5bd8ee30b4aa.png">

**Comment by Kcaden20** [comment]
Hey @xinemata Sorry I read your comment wrong originally. 

So because of how the pulling from the value is set-up (it turns it into a slug that can then be used to filter properly)—there's no way to then regain the capitalization that was entered originally. 

To switch over to a new `value` would wipe all the categories from the current contributions and require retesting the filtering logic to make sure it still works. 

I've gotten rid of the automatic lowering on the back end but let me know what you'd want to do for the front end?

**Comment by xinemata** [comment]
No worries. I think I’d prefer the way it is set up right now, so all lower case for bubble content. Thanks!
