### ISSUE TITLE
two column layout misalignment

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#5]
On the [Black Radical Translation page](https://criticalcode.recipes/contributions/black-radical-translation), the "Sonnet 116: Let me not to the marriage of true minds" and "Shakespeare’s 116th Sonnet in Black English Translation" headers might look better if they're top-aligned.  

<img width="1257" alt="Screen Shot 2022-06-21 at 11 23 59 AM" src="https://user-images.githubusercontent.com/9159424/174860915-a9db3fcb-dc78-4cf0-ae37-fedc9db76d0e.png">

**Comment by xinemata** [comment]
Same problem seems to be happening with images too on [the PAC-MOM entry](https://criticalcode.recipes/contributions/pac-mom-a-practical-rethinking-of-the-classics). 

<img width="1248" alt="Screen Shot 2022-06-21 at 9 06 27 PM" src="https://user-images.githubusercontent.com/9159424/174934878-e6af10b4-840c-48d9-8a1a-8a57a4308029.png">

**Comment by Kcaden20** [comment]
Fixed. This was due to some `section` styling implemented for one column layouts. See both instances fixed now.
![Screen Shot 2022-06-23 at 3 06 25 PM](https://user-images.githubusercontent.com/13590895/175378242-6cc50f42-81de-4fad-94ed-1d70099d8f6e.png)
![Screen Shot 2022-06-23 at 3 06 01 PM](https://user-images.githubusercontent.com/13590895/175378245-354bcfc2-1dd6-40a5-8400-aff98f2cdfd8.png)
